### PR TITLE
Fixed Traditional Chinese translation

### PR DESCRIPTION
**Pull request by plum7x**
the help still shows the English language. maybe incorrect path. please check it. thanks.

### CODE REVIEW

**Comment by woheller69** [comment]
probably the help file needs to be named **help-zh.html**.

The app uses:
language = getResources().getConfiguration().getLocales().get(0).getLanguage()

to get the language code, eg. de, en, etc

The fastlane files or for F-Droid only. I do not know if they show Chinese at all.

**Comment by woheller69** [comment]
maybe I will switch to 3 letter codes 

getISO3Language()

Do you know the code according to ISO 639-2

**Comment by woheller69** [comment]
can you try this (old) version and tell me the language code it shows when using help?

Uninstall
Remove .zip and install

https://github.com/woheller69/Arity/files/12504138/app-release.apk.zip

**Comment by plum7x** [comment]
> The fastlane files or for F-Droid only. I do not know if they show Chinese at all.

this is a typo, it should be zh-tw. i used it on other project.
this app on F-Droid still shows the information in English.

> Do you know the code according to ISO 639-2

twn

> can you try this (old) version and tell me the language code it shows when using help?

zh

**Pull request merged**
