### PR TITLE
Added Santali localization

### PR DESCRIPTION
**Pull request by Prasanta-Hembram**
Create strings.xml

### CODE REVIEW

**Comment by woheller69** [comment]
Do you also want to provide a translation of help? Help files are in 

https://github.com/woheller69/Arity/tree/master/app/src/main/assets

**Comment by Prasanta-Hembram** [comment]
sure @woheller69 , will commit soon.

**Comment by Prasanta-Hembram** [comment]
@woheller69 done..👍👍

**Comment by woheller69** [comment]
Please try if everything including help file works

Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Arity/files/12503282/app-release.apk.zip)

**Comment by Prasanta-Hembram** [comment]
Interface is displaying well. But, help files are still in english.
WhatsApp Image 2023-09-02 at 18 52 12
WhatsApp Image 2023-09-02 at 18 52 13

**Comment by woheller69** [comment]
Hope it works now. Please try again.
It should also show a message with the language code it finds. Does it show "Language: sat"?

[app-release.apk.zip](https://github.com/woheller69/Arity/files/12504138/app-release.apk.zip)

**Comment by Prasanta-Hembram** [comment]
> It should also show a message with the language code it finds. Does it show "Language: sat"?

Yes, now it's working and showing "Language: sat" when help page is opened. Thanks :-)

**Pull request merged**
